# Generated by Django 2.0.2 on 2018-04-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=150)),
                ('query', models.TextField()),
                ('image', models.ImageField(upload_to='uploads')),
            ],
            options={
                'db_table': 'support_query',
            },
        ),
        migrations.CreateModel(
            name='response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField()),
                ('query', models.ForeignKey(default=1, on_delete='CASCADE', to='dashboard.query')),
            ],
            options={
                'db_table': 'support_response',
            },
        ),
    ]
