# Generated by Django 2.0.2 on 2018-04-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20180426_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='responsedate',
            field=models.DateField(default='2018-04-26'),
        ),
    ]
