# Generated by Django 2.0.2 on 2018-04-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20180426_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='response',
            field=models.TextField(),
        ),
    ]
