# Generated by Django 2.0.2 on 2018-04-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20180426_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='responseUser',
            field=models.CharField(default='NULL', max_length=50),
        ),
        migrations.AlterField(
            model_name='response',
            name='response',
            field=models.CharField(max_length=500),
        ),
    ]
